apiRules:
    
  # Don't include samples
  - exclude:
      uidRegex: ^Samples
      type: Namespace

  # Don't include tests
  - exclude:
      uidRegex: ^LDtkUnity\.Tests
      type: Namespace


  # Exclude most of the standard schema data. Because it's Schema files, new updates will always change these files, so mark them here instead of giving them attributes
  - exclude: 
      uidRegex: ^LDtkUnity\.AllowedRefs
  - exclude: 
      uidRegex: ^LDtkUnity\.BgPos
  - exclude:
      uidRegex: ^LDtkUnity\.Checker
  - exclude:
      uidRegex: ^LDtkUnity\.EmbedAtlas
  - exclude:
      uidRegex: ^LDtkUnity\.ForcedRefs
  - exclude:
      uidRegex: ^LDtkUnity\.IdentifierStyle
  - exclude:
      uidRegex: ^LDtkUnity\.LimitBehavior
  - exclude:
      uidRegex: ^LDtkUnity\.LimitScope
  - exclude:
      uidRegex: ^LDtkUnity\.EditorDisplayMode
  - exclude:
      uidRegex: ^LDtkUnity\.EditorDisplayPos
  - exclude:
      uidRegex: ^LDtkUnity\.TypeEnum
  - exclude:
      uidRegex: ^LDtkUnity\.Flag
  - exclude:
      uidRegex: ^LDtkUnity\.Serialize
  - exclude:
      uidRegex: ^LDtkUnity\.TextLangageMode
  - exclude:
      uidRegex: ^LDtkUnity\.WorldLayout
  - exclude:
      uidRegex: ^LDtkUnity\.TileRenderMode
  - exclude:
      uidRegex: ^LDtkUnity\.ImageExportMode
  - exclude:
      uidRegex: ^LDtkUnity\.TextLanguageMode
  - exclude:
      uidRegex: ^LDtkUnity\.TileMode
  - exclude:
      uidRegex: ^LDtkUnity\.RenderMode
                      
  
      
  # Exclude Types with Unity's ExcludeFromDocs
  - exclude:
      hasAttribute:
        type: Type
        uid: UnityEngine.Internal.ExcludeFromDocsAttribute
        
  # Exclude Members with Unity's ExcludeFromDocs
  - exclude:
      hasAttribute:
        type: Member
        uid: UnityEngine.Internal.ExcludeFromDocsAttribute

  # Exclude the schema json data
  - exclude:
      hasAttribute:
        type: Property
        uid: Newtonsoft.Json.JsonPropertyAttribute
        
  # Exclude anything obsolete
  - exclude:
      hasAttribute:
        type: Type
        uid: System.ObsoleteAttribute
  # Exclude anything obsolete
  - exclude:
      hasAttribute:
        type: Property
        uid: System.ObsoleteAttribute
