name: Main Build Actions

on: [push, pull_request]

jobs:
  build:
    name: Project Builds
    runs-on: ubuntu-latest
    steps:
     # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

    # Cache library files
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

    # Test
      #- name: Run Tests
      #  uses: game-ci/unity-test-runner@v2
      #  env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #  with:
      #    githubToken: ${{ secrets.GITHUB_TOKEN }}

    # Build with 2019.3.0f1
      - name: Build Project
        uses: game-ci/unity-builder@v2
        
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2019.3.0f1
          targetPlatform: StandaloneWindows
          
    #  # Build with 2021.2.0f1
    #  - name: Build Project
    #    uses: game-ci/unity-builder@v2
    #    
    #    env:
    #      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    #    with:
    #      unityVersion: 2021.2.0f1
    #      targetPlatform: StandaloneWindows

    # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
